pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                echo 'I am buildingg all the day'
            }
        }
        stage('Test') {
            steps {
                echo 'I am testingg today'
            }
        }
        stage('Deploy') {
            steps {
                echo 'I am deploying'
            }
        }
        stage('Deploy againn') {
            steps {
                echo 'i am at last!!!!!!!!!!!'
            }
        }
    }
}
