pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                echo 'I am building'
            }
        }
        stage('Test') {
            steps {
                echo 'I am testing'
            }
        }
        stage('Deploy') {
            steps {
                echo 'I am deploying'
            }
        }
        stage('Delivery') {
            steps {
                echo 'I am delivering'
            }
        }
        stage('Deploy againn') {
            steps {
                echo 'i am at last!!!!!!!!!!!'
            }
        }
    }
}
