pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                echo 'I am buildingg'
            }
        }
        stage('Test') {
            steps {
                echo 'I am testingg'
            }
        }
        stage('Deploy') {
            steps {
                echo 'I am deploying'
            }
        }
        stage('Deploy againn') {
            steps {
                echo 'i am at last!!!!!!!!!!!'
            }
        }
    }
}
